# Generated by Django 4.0.6 on 2022-09-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('product_price', models.IntegerField(blank=True)),
                ('product_description', models.TextField(blank=True, max_length=2000)),
                ('product_date', models.DateTimeField(auto_now_add=True)),
                ('product_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
